language: python
dist: xenial
python:
  - "3.7-dev"
install:
  - pip3 install -r requirements.txt
  - pip3 install codecov
  - pip3 install coverage

script:
  - coverage run -m userbot ttt && coverage report
after_success:
  codecov
notifications:
  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify?secret=jeepeo12
    on_success: always
    on_failure: always
    on_start: never
deploy:
  provider: heroku
  api_key: e97e6133-943c-4bf3-a4ab-ec51da7a3114
  app: jeepeo






    

